    
name: Run PS scipt for file storage
on: workflow_dispatch
#   push:
#     paths:
#       - '.github/workflows/run-azure-login-action-integration-tests.yml'

jobs: 
  storage-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: 'Az CLI login with subscription'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Publish to Azure blob
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $context = New-AzStorageContext -StorageAccountName pstestaccount -SasToken "${{secrets.azureBlobQuerystring}}"
            Set-AzStorageBlobContent -File ./node-hello-master.zip -Container pstestcontainer -Context $context.Context -Force
            Set-AzStorageBlobContent -File ./node-hello-master1.zip -Container pstestcontainer -Context $context.Context -Force
            Set-AzStorageBlobContent -File ./node-hello-master2.zip -Container pstestcontainer -Context $context.Context -Force
          azPSVersion: "3.1.0"
          
#       - name: 'Az CLI login with subscription'
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}
#       - name: Publish to Azure blob
#         uses: azure/powershell@v1
#         with:
#           inlineScript: |
#            Get-AzContext
#           azPSVersion: '3.1.0'
#             $Context | Get-AzStorageBlob -Container "pstestcontainer" 
